In [ ]:
############################################################################################################################<3
############################################################################################################################<3
############################################################################################################################<3

                                    #FASE 0 DEFINICIÓN DE FUNCIONES

In [3]:
import numpy as np

tablero = np.arange(1, 226).reshape(15, 15)
print(tablero)

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40  41  42  43  44  45]
 [ 46  47  48  49  50  51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75]
 [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100 101 102 103 104 105]
 [106 107 108 109 110 111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130 131 132 133 134 135]
 [136 137 138 139 140 141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160 161 162 163 164 165]
 [166 167 168 169 170 171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190 191 192 193 194 195]
 [196 197 198 199 200 201 202 203 204 205 206 207 208 209 210]
 [211 212 213 214 215 216 217 218 219 220 221 222 223 224 225]]


In [4]:
import numpy as np

def tablero_numerado(lado=15):
    #  Así tenemos una lista de 225 números consecutivos, genera todos los números del 1 al 225 , el límite superior, 226, no se incluye
    tablero = np.arange(1, lado * lado + 1).reshape(lado, lado)
    return tablero

tablero = tablero_numerado(15)
print(tablero)

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40  41  42  43  44  45]
 [ 46  47  48  49  50  51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75]
 [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100 101 102 103 104 105]
 [106 107 108 109 110 111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130 131 132 133 134 135]
 [136 137 138 139 140 141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160 161 162 163 164 165]
 [166 167 168 169 170 171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190 191 192 193 194 195]
 [196 197 198 199 200 201 202 203 204 205 206 207 208 209 210]
 [211 212 213 214 215 216 217 218 219 220 221 222 223 224 225]]


In [5]:
tablero = tablero_numerado(15)

# Crear una copia independiente
tablero_dos = tablero.copy()
print(tablero_dos)

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40  41  42  43  44  45]
 [ 46  47  48  49  50  51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75]
 [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100 101 102 103 104 105]
 [106 107 108 109 110 111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130 131 132 133 134 135]
 [136 137 138 139 140 141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160 161 162 163 164 165]
 [166 167 168 169 170 171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190 191 192 193 194 195]
 [196 197 198 199 200 201 202 203 204 205 206 207 208 209 210]
 [211 212 213 214 215 216 217 218 219 220 221 222 223 224 225]]


In [6]:
tablero_alpha = tablero.copy()
tablero = tablero_numerado(15)

# Iterar y modificar solo la copia
for i in range(tablero_alpha.shape[0]):         #Filas
    for j in range(tablero_alpha.shape[1]):     #columnas
        if tablero_alpha[i, j] % 10 == 0:       # si es multip.lo de 10, lo cambia por 0
            tablero_alpha[i, j] = "0"

print("Tablero original :")
print(tablero)

print("Tablero copia modificado:")
print(tablero_alpha)

Tablero original :
[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40  41  42  43  44  45]
 [ 46  47  48  49  50  51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75]
 [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100 101 102 103 104 105]
 [106 107 108 109 110 111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130 131 132 133 134 135]
 [136 137 138 139 140 141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160 161 162 163 164 165]
 [166 167 168 169 170 171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190 191 192 193 194 195]
 [196 197 198 199 200 201 202 203 204 205 206 207 208 209 210]
 [211 212 213 214 215 216 217 218 219 220 221 222 223 224 225]]
Tablero copia modificado:
[[  1   2

In [7]:
tablero_dos = tablero.copy()
print(tablero_dos)

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40  41  42  43  44  45]
 [ 46  47  48  49  50  51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75]
 [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100 101 102 103 104 105]
 [106 107 108 109 110 111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130 131 132 133 134 135]
 [136 137 138 139 140 141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160 161 162 163 164 165]
 [166 167 168 169 170 171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190 191 192 193 194 195]
 [196 197 198 199 200 201 202 203 204 205 206 207 208 209 210]
 [211 212 213 214 215 216 217 218 219 220 221 222 223 224 225]]


In [17]:
tablero_dos = tablero.copy()

barco1 = [(0,1),(1,1)] #Aunque hayas cambiado a numeros hasta el 226, python sigue identificando sus valores, coordenadas (0,1),(1,1)
def coloca_barco(tablero_dos, barco):
    for pieza in barco:
        tablero_dos[pieza] = "0" 
    return tablero_dos

tablero_dos = coloca_barco(tablero_dos, barco1) #Tablero_dos NO crea un nuevo tablero a partir del tablero 
print(tablero_dos)

NameError: name 'tablero' is not defined

In [ ]:
#NO MODIFICAR CELDAS SUPERIORES YA QUE SI NO NUMPHY DETECTARÁ LA COPIA COMO VALORES ORIGINALES

In [9]:
tablero_dos = tablero.copy()

barco1 = [(0, 1), (1, 1)]
barco2 = [(1, 3), (1, 4), (1, 5), (1, 6)]

for barco in [barco1, barco2]:
    tablero_dos = coloca_barco(tablero_dos, barco)

print(tablero_dos)

[[  1   0   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 16   0  18   0   0   0   0  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40  41  42  43  44  45]
 [ 46  47  48  49  50  51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75]
 [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100 101 102 103 104 105]
 [106 107 108 109 110 111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130 131 132 133 134 135]
 [136 137 138 139 140 141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160 161 162 163 164 165]
 [166 167 168 169 170 171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190 191 192 193 194 195]
 [196 197 198 199 200 201 202 203 204 205 206 207 208 209 210]
 [211 212 213 214 215 216 217 218 219 220 221 222 223 224 225]]


In [ ]:
import numpy as np

def tablero_numerado(lado=15):
    tablero = np.arange(1, lado * lado + 1).reshape(lado, lado)
    return tablero.astype(object)

def coloca_barco(tablero, barco):
    for pieza in barco:
        tablero[pieza] = "🚢"
    return tablero

# Crear tablero base y colocar barcos
tablero_dos = tablero_numerado(15)
barco1 = [(0, 1), (1, 1)]
barco2 = [(1, 3), (1, 4), (1, 5), (1, 6)]
for barco in [barco1, barco2]:
    tablero_dos = coloca_barco(tablero_dos, barco)


In [ ]:
# Función de disparo 
def recibir_disparo(tablero_dos, coordenada):
    if tablero_dos[coordenada] == "🚢":
        tablero_dos[coordenada] = "💥"
        print("¡Tocado!")
    elif tablero_dos[coordenada] == "💥" or tablero_dos[coordenada] == "🌊":
        print("Ya has disparado aquí, elige otra casilla.")
    else:
        tablero_dos[coordenada] = "🌊"
        print("Agua")

In [ ]:
# --- Disparos de ejemplo ---
recibir_disparo(tablero_dos, (0, 1))  # Tocado
recibir_disparo(tablero_dos, (2, 2))  # Agua
recibir_disparo(tablero_dos, (0, 1))  # Repetido

print("\nTablero después de los disparos:")
print(tablero_dos)

¡Tocado!
Agua
Ya has disparado aquí, elige otra casilla.

Tablero después de los disparos:
[[1 '💥' 3 4 5 6 7 8 9 10 11 12 13 14 15]
 [16 '🚢' 18 '🚢' '🚢' '🚢' '🚢' 23 24 25 26 27 28 29 30]
 [31 32 '🌊' 34 35 36 37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70 71 72 73 74 75]
 [76 77 78 79 80 81 82 83 84 85 86 87 88 89 90]
 [91 92 93 94 95 96 97 98 99 100 101 102 103 104 105]
 [106 107 108 109 110 111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130 131 132 133 134 135]
 [136 137 138 139 140 141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160 161 162 163 164 165]
 [166 167 168 169 170 171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190 191 192 193 194 195]
 [196 197 198 199 200 201 202 203 204 205 206 207 208 209 210]
 [211 212 213 214 215 216 217 218 219 220 221 222 223 224 225]]


In [ ]:
#Mejora del output para que sea menos monotono y mas interactivo
import numpy as np

tablero = np.arange(1, 226).reshape(15, 15).astype(object)

barco1 = [(0, 1), (1, 1)]
barco2 = [(1, 3), (1, 4), (1, 5), (1, 6)]
for barco in [barco1, barco2]:
    for pieza in barco:
        tablero[pieza] = "🚢"

def recibir_disparo(tablero_dos, coordenada):
    if tablero_dos[coordenada] == "🚢":
        tablero_dos[coordenada] = "💥"
        print("💥 ¡Tocado!")
    elif tablero_dos[coordenada] in ["💥", "🌊"]:
        print("⚠️ Ya has disparado aquí, elige otra casilla.")
    else:
        tablero_dos[coordenada] = "🌊"
        print("🌊 Agua")

In [ ]:
# --- Disparos de ejemplo ---
recibir_disparo(tablero, (0, 1))
recibir_disparo(tablero, (2, 2))
recibir_disparo(tablero, (0, 1))


print("\n🔹 Tablero después de los disparos:\n")

for fila in tablero:
    print(" ".join(f"{str(x).zfill(3) if isinstance(x, int) else x:>3}" for x in fila))

💥 ¡Tocado!
🌊 Agua
⚠️ Ya has disparado aquí, elige otra casilla.

🔹 Tablero después de los disparos:

001   💥 003 004 005 006 007 008 009 010 011 012 013 014 015
016   🚢 018   🚢   🚢   🚢   🚢 023 024 025 026 027 028 029 030
031 032   🌊 034 035 036 037 038 039 040 041 042 043 044 045
046 047 048 049 050 051 052 053 054 055 056 057 058 059 060
061 062 063 064 065 066 067 068 069 070 071 072 073 074 075
076 077 078 079 080 081 082 083 084 085 086 087 088 089 090
091 092 093 094 095 096 097 098 099 100 101 102 103 104 105
106 107 108 109 110 111 112 113 114 115 116 117 118 119 120
121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
136 137 138 139 140 141 142 143 144 145 146 147 148 149 150
151 152 153 154 155 156 157 158 159 160 161 162 163 164 165
166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
181 182 183 184 185 186 187 188 189 190 191 192 193 194 195
196 197 198 199 200 201 202 203 204 205 206 207 208 209 210
211 212 213 214 215 216 217 218 219 220 221 222 223 224 225

In [ ]:
# DAMOS VALORES COHERENTES PARA QUE EL OUTPUT SEA ORDENADO
def recibir_disparo(tablero_dos, coordenada):
    if tablero_dos[coordenada] == "BBB":
        tablero_dos[coordenada] = "X0X"
        print("💥 ¡Tocado!")
    elif tablero_dos[coordenada] in ["X0X", "AAA"]:
        print("⚠️ Ya has disparado aquí, elige otra casilla.")
    else:
        tablero_dos[coordenada] = "000"
        print("🌊 Agua")

In [ ]:
# --- Ejemplo de disparos ---
recibir_disparo(tablero, (0, 1))  # Tocado
recibir_disparo(tablero, (2, 2))  # Agua
recibir_disparo(tablero, (0, 1))  # Repetido

print("\n🔹 Tablero después de los disparos:\n")
#ARREGLAMOS LA ALINEACIÓN DEL OUTPUT
for fila in tablero:
    print(" ".join(f"{str(x).zfill(3) if isinstance(x, int) else f'{x:>3}'}" for x in fila))


💥 ¡Tocado!
🌊 Agua
⚠️ Ya has disparado aquí, elige otra casilla.

🔹 Tablero después de los disparos:

001 X0X 003 004 005 006 007 008 009 010 011 012 013 BBB 015
016 BBB 018 BBB BBB BBB BBB 023 024 025 026 027 028 BBB 030
031 032 000 034 035 036 037 038 039 040 041 042 043 BBB 045
046 047 048 049 050 051 052 053 054 055 056 057 058 BBB 060
061 062 063 064 065 066 067 068 069 070 071 072 073 BBB 075
076 077 078 079 080 081 082 083 084 085 BBB 087 088 089 090
091 092 093 094 095 096 097 098 099 100 BBB 102 103 104 105
106 107 108 109 110 111 112 113 114 115 BBB 117 118 119 120
121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
136 137 138 139 140 141 142 143 144 145 146 147 148 149 150
151 152 153 154 155 156 157 158 159 160 161 162 163 164 165
166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
181 182 183 184 185 186 187 188 189 190 191 192 193 194 195
196 197 198 199 200 201 202 203 204 205 206 207 208 209 210
211 212 213 214 215 216 217 218 219 220 221 222 223 224 225

In [ ]:
# 🧭 Leyenda del tablero:
# Tocado → "X0X"
# Barco  → "BBB"
# Agua   → "000"
# Number → 

BARCO = "BBB"
TOCADO = "X0X"
AGUA = "AAA"

In [22]:
tablero == "X0X"

array([[False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, Fa

In [24]:
tablero == "000"
#Miramos el agua, es importante hidratarse bien

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False],
       [False, False, Fa

In [ ]:
# Función para reparar barcos y limpiar aguas 
def arregla_barcos(tablero):
    for i in range(tablero.shape[0]):
        for j in range(tablero.shape[1]):
            valor = tablero[i, j]
            if valor == "X0X":  # Repara barcos dañados
                tablero[i, j] = "BBB"
            elif valor == "000":  # Limpia aguas y repone número original
                tablero[i, j] = str(i * tablero.shape[1] + j + 1).zfill(3)
    return tablero

In [ ]:
# Aplicar reparación 
tablero_reparado = arregla_barcos(tablero)


print("\n🔹 Tablero reparado y limpio:\n")
for fila in tablero_reparado:
    print(" ".join(f"{str(x).zfill(3) if isinstance(x, int) else f'{x:>3}'}" for x in fila))



🔹 Tablero reparado y limpio:

001 BBB 003 004 005 006 007 008 009 010 011 012 013 014 015
016 BBB 018 BBB BBB BBB BBB 023 024 025 026 027 028 029 030
031 032 033 034 035 036 037 038 039 040 041 042 043 044 045
046 047 048 049 050 051 052 053 054 055 056 057 058 059 060
061 062 063 064 065 066 067 068 069 070 071 072 073 074 075
076 077 078 079 080 081 082 083 084 085 086 087 088 089 090
091 092 093 094 095 096 097 098 099 100 101 102 103 104 105
106 107 108 109 110 111 112 113 114 115 116 117 118 119 120
121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
136 137 138 139 140 141 142 143 144 145 146 147 148 149 150
151 152 153 154 155 156 157 158 159 160 161 162 163 164 165
166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
181 182 183 184 185 186 187 188 189 190 191 192 193 194 195
196 197 198 199 200 201 202 203 204 205 206 207 208 209 210
211 212 213 214 215 216 217 218 219 220 221 222 223 224 225


In [ ]:
def coloca_barco_plus(tablero, barco):
    """
    Coloca un barco en el tablero solo si todas las posiciones son válidas.
    Devuelve el nuevo tablero si se puede colocar, o False si no.
    """
    tablero_temp = tablero.copy()
    num_max_filas, num_max_columnas = tablero.shape

    for pieza in barco:
        fila, columna = pieza

        # Verificar límites del tablero
        if fila < 0 or fila >= num_max_filas:
            print(f"❌ No puedo poner la pieza {pieza}: fuera del tablero (fila inválida)")
            return False
        if columna < 0 or columna >= num_max_columnas:
            print(f"❌ No puedo poner la pieza {pieza}: fuera del tablero (columna inválida)")
            return False

        # Verificar colisiones con otros barcos
        if tablero[fila, columna] in ["BBB", "X0X"]:
            print(f"⚠️ No puedo poner la pieza {pieza}: ya hay un barco en esa posición")
            return False

        # Si todo está bien, colocar barco en el tablero temporal
        tablero_temp[fila, columna] = "BBB"

    print(f"✅ Barco colocado en posiciones: {barco}")
    return tablero_temp


In [ ]:
barco3 = [(3, 10), (3, 11), (3, 12)]
nuevo_tablero = coloca_barco_plus(tablero, barco3)

# Actualizar si la colocación fue válida 
if isinstance(nuevo_tablero, np.ndarray):
    tablero = nuevo_tablero

# Imprimir tablero alineado 
print("\n🔹 Tablero después de colocar el nuevo barco:\n")

for fila in tablero:
    print(" ".join(f"{str(x).zfill(3) if isinstance(x, int) else f'{x:>3}'}" for x in fila))

✅ Barco colocado en posiciones: [(3, 10), (3, 11), (3, 12)]

🔹 Tablero después de colocar el nuevo barco:

001 BBB 003 004 005 006 007 008 009 010 011 012 013 014 015
016 BBB 018 BBB BBB BBB BBB 023 024 025 026 027 028 029 030
031 032 033 034 035 036 037 038 039 040 041 042 043 044 045
046 047 048 049 050 051 052 053 054 055 BBB BBB BBB 059 060
061 062 063 064 065 066 067 068 069 070 071 072 073 074 075
076 077 078 079 080 081 082 083 084 085 086 087 088 089 090
091 092 093 094 095 096 097 098 099 100 101 102 103 104 105
106 107 108 109 110 111 112 113 114 115 116 117 118 119 120
121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
136 137 138 139 140 141 142 143 144 145 146 147 148 149 150
151 152 153 154 155 156 157 158 159 160 161 162 163 164 165
166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
181 182 183 184 185 186 187 188 189 190 191 192 193 194 195
196 197 198 199 200 201 202 203 204 205 206 207 208 209 210
211 212 213 214 215 216 217 218 219 220 221 222 223 2

In [ ]:
def coloca_barco_plus(tablero, barco):
    """
    Coloca un barco en el tablero solo si todas las posiciones son válidas.
    Si hay un error, muestra un aviso y devuelve el tablero original sin modificar.
    """
    tablero_temp = tablero.copy()
    num_max_filas, num_max_columnas = tablero.shape

    for pieza in barco:
        fila, columna = pieza

        # Verificar límites del tablero
        if fila < 0 or fila >= num_max_filas:
            print(f"❌ No puedo poner la pieza {pieza}: fuera del tablero (fila inválida)")
            print("⛔ Volviendo al tablero original...")
            return tablero  # ← Mantiene el original

        if columna < 0 or columna >= num_max_columnas:
            print(f"❌ No puedo poner la pieza {pieza}: fuera del tablero (columna inválida)")
            print("⛔ Volviendo al tablero original...")
            return tablero  

        # Verificar colisiones con otros barcos
        if tablero[fila, columna] in ["BBB", "X0X"]:
            print(f"⚠️ No puedo poner la pieza {pieza}: ya hay un barco en esa posición")
            print("⛔ Volviendo al tablero original...")
            return tablero 

        # Si todo está bien, colocar barco temporalmente
        tablero_temp[fila, columna] = "BBB"

    print(f"✅ Barco colocado correctamente en posiciones: {barco}")
    return tablero_temp


⚠️ No puedo poner la pieza (3, 10): ya hay un barco en esa posición
⛔ Volviendo al tablero original...
❌ No puedo poner la pieza (14, 15): fuera del tablero (columna inválida)
⛔ Volviendo al tablero original...

🔹 Tablero final:

001 BBB 003 004 005 006 007 008 009 010 011 012 013 014 015
016 BBB 018 BBB BBB BBB BBB 023 024 025 026 027 028 029 030
031 032 033 034 035 036 037 038 039 040 041 042 043 044 045
046 047 048 049 050 051 052 053 054 055 BBB BBB BBB 059 060
061 062 063 064 065 066 067 068 069 070 071 072 073 074 075
076 077 078 079 080 081 082 083 084 085 086 087 088 089 090
091 092 093 094 095 096 097 098 099 100 101 102 103 104 105
106 107 108 109 110 111 112 113 114 115 116 117 118 119 120
121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
136 137 138 139 140 141 142 143 144 145 146 147 148 149 150
151 152 153 154 155 156 157 158 159 160 161 162 163 164 165
166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
181 182 183 184 185 186 187 188 189 190 191 192 19

In [ ]:
# Intentar colocar un nuevo barco (correcto) 
barco3 = [(3, 10), (3, 11), (3, 12)]
tablero = coloca_barco_plus(tablero, barco3)

# Intentar colocar un barco fuera del tablero (incorrecto) 
barco_mal = [(14, 15), (14, 16)]  # 16 está fuera del tablero
tablero = coloca_barco_plus(tablero, barco_mal)


print("\n🔹 Tablero final:\n")

for fila in tablero:
    print(" ".join(f"{str(x).zfill(3) if isinstance(x, int) else f'{x:>3}'}" for x in fila))

NameError: name 'tablero' is not defined

In [ ]:
# Nueva función: crear barco aleatorio y colocarlo 
def crea_barco_aleatorio(tablero, eslora=4, num_intentos=100):
    """
    Crea y coloca un barco de forma aleatoria en el tablero.
    Si no se puede colocar tras varios intentos, muestra aviso y devuelve el tablero sin cambios.
    """
    num_max_filas, num_max_columnas = tablero.shape

    for intento in range(num_intentos):
        barco = []

        # Escoger posición inicial
        pieza_original = (random.randint(0, num_max_filas - 1), random.randint(0, num_max_columnas - 1))
        orientacion = random.choice(["N", "S", "E", "O"])

        fila, columna = pieza_original
        barco.append(pieza_original)

        # Construir barco según orientación
        for _ in range(eslora - 1):
            if orientacion == "N":
                fila -= 1
            elif orientacion == "S":
                fila += 1
            elif orientacion == "E":
                columna += 1
            elif orientacion == "O":
                columna -= 1
            barco.append((fila, columna))

        # Intentar colocar barco
        tablero_temp = coloca_barco_plus(tablero, barco)
        if not np.array_equal(tablero_temp, tablero):  # Si se modificó, fue exitoso
            return tablero_temp

        print(f"🔁 Intento {intento+1}/{num_intentos}: no se pudo colocar el barco. Reintentando...")

    print("🚫 No se pudo colocar el barco tras varios intentos.")
    return tablero



Ahora lo iteramos todo junto ya que si no da error

In [ ]:

# Ejemplo de uso 
tablero = crea_barco_aleatorio(tablero, eslora=5)
tablero = crea_barco_aleatorio(tablero, eslora=3)


✅ Barco colocado correctamente en posiciones: [(13, 9), (12, 9), (11, 9), (10, 9), (9, 9)]
✅ Barco colocado correctamente en posiciones: [(6, 8), (5, 8), (4, 8)]

🔹 Tablero final con barcos aleatorios:

001 BBB 003 004 005 006 007 008 009 010 011 012 013 014 015
016 BBB 018 BBB BBB BBB BBB 023 024 025 026 027 028 029 030
031 032 033 034 035 036 037 038 039 040 041 042 043 044 045
046 047 048 049 050 051 052 053 054 055 056 057 058 059 060
061 062 063 064 065 066 067 068 BBB 070 071 072 073 074 075
076 077 078 079 080 081 082 083 BBB 085 086 087 088 089 090
091 092 093 094 095 096 097 098 BBB 100 101 102 103 104 105
106 107 108 109 110 111 112 113 114 115 116 117 118 119 120
121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
136 137 138 139 140 141 142 143 144 BBB 146 147 148 149 150
151 152 153 154 155 156 157 158 159 BBB 161 162 163 164 165
166 167 168 169 170 171 172 173 174 BBB 176 177 178 179 180
181 182 183 184 185 186 187 188 189 BBB 191 192 193 194 195
196 197 198 199 2

In [66]:
tablero = crea_barco_aleatorio(tablero, eslora = 6)

❌ No puedo poner la pieza (15, 6): fuera del tablero.
⛔ Volviendo al tablero original...
🔁 Intento 1/100: no se pudo colocar el barco. Reintentando...
❌ No puedo poner la pieza (15, 13): fuera del tablero.
⛔ Volviendo al tablero original...
🔁 Intento 2/100: no se pudo colocar el barco. Reintentando...
❌ No puedo poner la pieza (10, -1): fuera del tablero.
⛔ Volviendo al tablero original...
🔁 Intento 3/100: no se pudo colocar el barco. Reintentando...
⚠️ No puedo poner la pieza (1, 1): ya hay un barco ahí.
⛔ Volviendo al tablero original...
🔁 Intento 4/100: no se pudo colocar el barco. Reintentando...
⚠️ No puedo poner la pieza (10, 9): ya hay un barco ahí.
⛔ Volviendo al tablero original...
🔁 Intento 5/100: no se pudo colocar el barco. Reintentando...
⚠️ No puedo poner la pieza (1, 1): ya hay un barco ahí.
⛔ Volviendo al tablero original...
🔁 Intento 6/100: no se pudo colocar el barco. Reintentando...
❌ No puedo poner la pieza (11, -1): fuera del tablero.
⛔ Volviendo al tablero origina

In [ ]:
print("\n🔹 Tablero final con barcos aleatorios:\n")
for fila in tablero:
    print(" ".join(f"{str(x).zfill(3) if isinstance(x, int) else f'{x:>3}'}" for x in fila))


❌ No puedo poner la pieza (8, -1): fuera del tablero.
⛔ Volviendo al tablero original...
🔁 Intento 1/100: no se pudo colocar el barco. Reintentando...
❌ No puedo poner la pieza (14, -1): fuera del tablero.
⛔ Volviendo al tablero original...
🔁 Intento 2/100: no se pudo colocar el barco. Reintentando...
❌ No puedo poner la pieza (1, 15): fuera del tablero.
⛔ Volviendo al tablero original...
🔁 Intento 3/100: no se pudo colocar el barco. Reintentando...
✅ Barco colocado correctamente en posiciones: [(4, 13), (3, 13), (2, 13), (1, 13), (0, 13)]
✅ Barco colocado correctamente en posiciones: [(5, 10), (6, 10), (7, 10)]

🔹 Tablero final con barcos aleatorios:

001 BBB 003 004 005 006 007 008 009 010 011 012 013 BBB 015
016 BBB 018 BBB BBB BBB BBB 023 024 025 026 027 028 BBB 030
031 032 033 034 035 036 037 038 039 040 041 042 043 BBB 045
046 047 048 049 050 051 052 053 054 055 056 057 058 BBB 060
061 062 063 064 065 066 067 068 069 070 071 072 073 BBB 075
076 077 078 079 080 081 082 083 084 085

In [ ]:
############################################################################################################################<3
############################################################################################################################<3
############################################################################################################################<3

                                    #FASE 1 MVP

In [ ]:
# Mostrar tablero inicial
def mostrar_tablero(tablero):
    for fila in tablero:
        print(" ".join(f"{str(x).zfill(3) if isinstance(x, int) else x:>3}" for x in fila))
    print()




In [ ]:
# Pedir Coordenadas del jugador formato(4,5)
def pedir_coord():
    try:
        entrada = input("Introduce coordenada : ")
        f, c = map(int, entrada.replace(" ", "").split(","))
        return (f, c)
    except:
        print("Formato incorrecto (ej: 3,5)")
        return pedir_coord()


In [ ]:

# Coordenadas del jugador + CODIGO DE SALIR 
def pedir_coord():
    entrada = input("Introduce coordenada (fila,columna) o escribe 'salir' para terminar: ").strip().lower()
    if entrada == "salir":
        return "salir"
    try:
        f, c = map(int, entrada.replace(" ", "").split(","))
        return (f, c)
    except:
        print("❌ Formato incorrecto. Usa: fila,columna (ej: 3,5)")
        return pedir_coord()


In [ ]:
# Iniciar tablero
tab_jugador = crear_tablero()
tab_cpu = crear_tablero()


In [ ]:
# Colocar barcos (2)
tab_jugador = crea_barco_aleatorio(tab_jugador, 4)
tab_jugador = crea_barco_aleatorio(tab_jugador, 3)
tab_cpu = crea_barco_aleatorio(tab_cpu, 4)
tab_cpu = crea_barco_aleatorio(tab_cpu, 3)

print("🚢 ¡A HUNDIR LA FLOTA! 🚢")

In [ ]:
# Bucle Jugable
while True:
    print("\nTu tablero:")
    mostrar_tablero(tab_jugador)
    print("Disparos a CPU:")
    mostrar_tablero(tab_cpu)

    # Turno jugador
    coord = pedir_coord()
    recibir_disparo(tab_cpu, coord)

    # ¿CPU hundida?
    if not np.any(tab_cpu == BARCO):
        print("🏆 ¡VAYA PALIZA!")
        break

    # Turno CPU
    cpu_coord = (random.randint(0, 14), random.randint(0, 14))
    print(f"🎯 CPU dispara a {cpu_coord}")
    recibir_disparo(tab_jugador, cpu_coord)

    # ¿Jugador hundido?
    if not np.any(tab_jugador == BARCO):
        print("💀 Has perdido...")
        break

In [9]:
python hundirlaflota.py


⛔ El barco se sale del tablero.
⛔ El barco se sale del tablero.
🚢 ¡Comienza la batalla! 🚢

Tu tablero:
001 002 003 004 005 006 007 008 009 010 011 012 013 014 015
016 017 018 019 020 021 022 023 024 025 026 027 028 029 030
031 032 033 034 035 036 037 038 039 040 041 042 043 044 045
046 047 048 049 050 051 052 053 054 055 056 057 058 059 060
061 062 063 064 065 066 067 068 069 070 071 072 073 074 075
076 077 078 079 080 081 082 083 084 085 086 087 088 089 090
091 092 093 094 095 096 097 098 099 100 101 102 103 104 105
106 107 108 109 110 111 112 113 114 115 116 117 118 119 120
121 122 123 124 125 126 127 128 BBB 130 131 132 133 134 135
136 137 138 139 140 141 142 143 BBB 145 146 147 148 149 150
151 152 153 154 155 156 157 158 BBB 160 161 162 163 164 165
BBB BBB BBB BBB 170 171 172 173 174 175 176 177 178 179 180
181 182 183 184 185 186 187 188 189 190 191 192 193 194 195
196 197 198 199 200 201 202 203 204 205 206 207 208 209 210
211 212 213 214 215 216 217 218 219 220 221 222 223 224 2

ValueError: too many values to unpack (expected 2)