![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [4]:
!pip install numpy



[notice] A new release of pip is available: 23.0.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np 

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [8]:
import numpy as np
mi_array = np.array([8, 7, 6, 5, 4]) # ·# definimos el array primero 😅
print("array:", mi_array[0:2]) # ·# pillamos solo [8 7]


array: [8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [9]:
import numpy as np
mi_array = np.array([2, 1, 0, -1, -2]) 
print("array:", mi_array[0:3]) 


array: [2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [10]:
import numpy as np
mi_matriz = np.arange(1, 21).reshape(4, 5) #A Range == Un Rango
print("array:", mi_matriz)


array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [ ]:
mi_submatriz = mi_matriz[:2, :2] 
print("array:", np.array2string(mi_submatriz))

#como se alinea?????


array: [[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [22]:
mi_submatriz = mi_matriz[[0,2], :][:, [0,2,4]] # filas 0 y 2, columnas 0,2,4
print("array:", np.array2string(mi_submatriz))

array: [[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [ ]:
mi_submatriz = mi_matriz[:3, :]  # primeras 3 filas
mi_submatriz = mi_submatriz[:, ::-1]  # invertir columnas
print("array:", mi_submatriz) 


array: [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


In [ ]:
      Columnas
       0   1   2   3
Fila 0 [a00 a01 a02 a03]
Fila 1 [a10 a11 a12 a13]
Fila 2 [a20 a21 a22 a23]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [24]:
import numpy as np

mi_array = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

#  usar fancy indexing con máscara booleana disfrazada de detective 
detective = np.array([animal == "Loro" for animal in mi_array])
solo_loros = mi_array[detective]

print("¡Detective dice que los loros son:", solo_loros, "🦜🕵️‍♂️")


¡Detective dice que los loros son: ['Loro' 'Loro'] 🦜🕵️‍♂️


In [25]:
import numpy as np

mi_array = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

# Obtener índices donde hay loros
indices_loros = np.where(mi_array == "Loro")[0]

print("Los loros están en las posiciones:", indices_loros, "🦜🔍")


Los loros están en las posiciones: [0 3] 🦜🔍


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [26]:
import numpy as np

mi_secuencia = np.arange(1, 21)  
mi_array = mi_secuencia.reshape(2, 5, 2) # transformar en 2 matrices 5x2

print("array:", mi_array)


array: [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [28]:
import numpy as np

mi_matriz = np.arange(1, 21).reshape(4, 5)
mi_array = np.flip(mi_matriz, axis=1)  # invertir columnas
mi_array = np.flip(mi_array, axis=0)   # invertir filas para efecto invertido total
print("array:", mi_array)  

array: [[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [ ]:
import numpy as np

mi_array[3] = 1
print("array:", mi_array)  
print("tamaño en bytes:", mi_array.nbytes)  


array: [0 0 0 1 0 0 0 0 0 0]
tamaño en bytes: 80


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [31]:
import numpy as np

mi_vector = np.arange(10, 50)[::-1]
print("vector:", mi_vector)  


vector: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [32]:
import numpy as np

mi_vector = np.array([1,2,0,0,4,0])
indices_no_ceros = np.nonzero(mi_vector)[0]  # Aquí numpy hace magia
print("indices:", indices_no_ceros)  


indices: [0 1 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [33]:
import numpy as np

mi_matriz = np.random.randint(0, 100, size=(10,10))
valor_min = mi_matriz.min()
valor_max = mi_matriz.max()
print("min:", valor_min, "max:", valor_max) 


min: 2 max: 99


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [35]:
import numpy as np

mi_vector = np.random.rand(30)
media = mi_vector.mean()
print("media:", media) 


media: 0.4561313299088055


Un vector es básicamente una lista ordenada de números. 
En numpy es un array de una sola dimensión; piensa en él como una fila de casillas donde cada casilla guarda un número.

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [37]:
import numpy as np

mi_matriz = np.pad(np.zeros((4,4)), pad_width=1, constant_values=1)  # borde de 1s interior 0s
print("array:", mi_matriz) 


array: [[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [38]:
import numpy as np

mi_matriz = np.indices((8,8)).sum(axis=0) % 2  #????
print("array:", mi_matriz)

array: [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [ ]:
import numpy as np

bloque = np.array([[0,1],[1,0]])
mi_matriz = np.tile(bloque, (4,4))  # repite el bloque 4x4 para formar 8x8
print("array:", mi_matriz) 


array: [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


: 

## Ejercicio 9
Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [1]:
import numpy as np

matriz = np.random.rand(5, 5)
print("Matriz original:\n", matriz)

media = np.mean(matriz)
desviacion = np.std(matriz)

# Estandarizar la matriz
matriz_estandarizada = (matriz - media) / desviacion
print("\nMatriz estandarizada:\n", matriz_estandarizada)


print("\nMedia de la matriz estandarizada:", np.mean(matriz_estandarizada))
print("Desviación estándar de la matriz estandarizada:", np.std(matriz_estandarizada))

Matriz original:
 [[0.98075631 0.84472225 0.24607377 0.40103817 0.47365528]
 [0.50303305 0.63640236 0.69255597 0.71887512 0.28441936]
 [0.63439836 0.80597534 0.1247379  0.36030118 0.66897403]
 [0.26576637 0.45926022 0.29345396 0.39293531 0.77997458]
 [0.77362788 0.59573814 0.96667208 0.60090388 0.28482346]]

Matriz estandarizada:
 [[ 1.84256216  1.25855677 -1.31149017 -0.6462153  -0.33446409]
 [-0.20834295  0.36422243  0.6052945   0.71828474 -1.1468694 ]
 [ 0.35561911  1.09221313 -1.83239501 -0.82110254  0.5040553 ]
 [-1.22694825 -0.39626327 -1.10808312 -0.68100157  0.98058974]
 [ 0.95334284  0.18964761  1.7820974   0.21182454 -1.1451346 ]]

Media de la matriz estandarizada: 2.6645352591003756e-16
Desviación estándar de la matriz estandarizada: 1.0


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [4]:
import numpy as np

arr = np.arange(0, 11)
print("Array original:\n", arr)



Array original:
 [ 0  1  2  3  4  5  6  7  8  9 10]


In [5]:
arr_modificado = arr.copy()
arr_modificado[(arr_modificado >= 3) & (arr_modificado <= 8)] = -1
print("\nArray con valores entre 3 y 8 reemplazados por -1:\n", arr_modificado)


Array con valores entre 3 y 8 reemplazados por -1:
 [ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [6]:
arr_negado = arr.copy()
arr_negado[(arr_negado >= 3) & (arr_negado <= 8)] *= -1
print("\nArray con valores entre 3 y 8 negados:\n", arr_negado)


Array con valores entre 3 y 8 negados:
 [ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
